version: '3'

services:
  db:
    image: mongo
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27018:27017"
    restart: always
    networks:
      connect-network:
        ipv4_address: 172.77.0.2

  app:
    build: .
    ports:
      - "8080:3000"
    restart: always
    networks:
      connect-network:
        ipv4_address: 172.77.0.3
    depends_on:
      - db

networks:
  connect-network:
    ipam:
      driver: default
      config:
        - subnet: 172.77.0.0/16
