version: '3'

services:
  db:
    image: mongo
    networks:
      connect-network:
        ipv4_address: 172.77.0.2
    ports:
      - "27018:27017"
  app:
    build: .
    networks:
      connect-network:
        ipv4_address: 172.77.0.3
    ports:
      - "8080:3000"

networks:
  connect-network:
    ipam:
      driver: default
      config:
        - subnet: 172.77.0.0/16
